Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [20]:
import numpy as np

def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        a = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        a = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return a

inpt = np.array([1,2,3,4,5])
N = 5
matx_dec_order = gen_vander_matrix(inpt,N,False)
matx_inc_order = gen_vander_matrix(inpt,N,True)

print("input array is:",inpt,"\n")
print("Number of columns in output matrix:",N,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",matx_inc_order,"\n")

input array is: [1 2 3 4 5] 

Number of columns in output matrix: 5 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 



In [19]:
inpt = np.array([1,2,3,4,5])
N = 5
matx_dec_order = gen_vander_matrix(inpt,N,False)
matx_inc_order = gen_vander_matrix(inpt,N,True)

print("input array is:",inpt,"\n")
print("Number of columns in output matrix should be:",N,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",matx_inc_order,"\n")

input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order of powers:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 



In [23]:
x=np.array([1,2,3,4,5])
x=np.vander(x)
x

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [24]:
x=np.array([1,2,3,4,5]) 
N=5 
matrix1 = np.vander(x,N,increasing=True) 
matrix1

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [7]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

print(moving_average(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
